In [27]:
# import numpy and pandas

import numpy as np
import pandas as pd
import re

In [38]:
# Load the data percent-forst-cover.csv

df = pd.read_csv('./data/percent-forest-cover.csv')
df.head(10)

       Country Code  Year  Forestcover
0  Afghanistan  AFG  1990     1.850994
1  Afghanistan  AFG  1991     1.850994
2  Afghanistan  AFG  1992     1.850994
3  Afghanistan  AFG  1993     1.850994
4  Afghanistan  AFG  1994     1.850994
5  Afghanistan  AFG  1995     1.850994
6  Afghanistan  AFG  1996     1.850994
7  Afghanistan  AFG  1997     1.850994
8  Afghanistan  AFG  1998     1.850994
9  Afghanistan  AFG  1999     1.850994

In [39]:
df[df["Country"] == "United States of America"]

                       Country Code  Year  Forestcover
6773  United States of America  USA  1630    46.179039
6774  United States of America  USA  1920    31.853560
6775  United States of America  USA  1940    32.604614
6776  United States of America  USA  1953    32.781333
6777  United States of America  USA  1963    33.267310
6778  United States of America  USA  1977    32.781333
6779  United States of America  USA  1987    32.383716
6780  United States of America  USA  1990    33.063968
6781  United States of America  USA  1991    33.075840
6782  United States of America  USA  1992    33.087712
6783  United States of America  USA  1993    33.099584
6784  United States of America  USA  1994    33.111457
6785  United States of America  USA  1995    33.123329
6786  United States of America  USA  1996    33.135201
6787  United States of America  USA  1997    33.147073
6788  United States of America  USA  1998    33.158945
6789  United States of America  USA  1999    33.170818
6790  United States of America  USA  2000    33.182690
6791  United States of America  USA  2001    33.239361
6792  United States of America  USA  2002    33.296033
6793  United States of America  USA  2003    33.352705
6794  United States of America  USA  2004    33.409377
6795  United States of America  USA  2005    33.466048
6796  United States of America  USA  2006    33.522720
6797  United States of America  USA  2007    33.579392
6798  United States of America  USA  2008    33.636064
6799  United States of America  USA  2009    33.692735
6800  United States of America  USA  2010    33.749407
6801  United States of America  USA  2011    33.779470
6802  United States of America  USA  2012    33.809533
6803  United States of America  USA  2013    33.839596
6804  United States of America  USA  2014    33.869659
6805  United States of America  USA  2015    33.899723
6806  United States of America  USA  2016    33.893163
6807  United States of America  USA  2017    33.886604
6808  United States of America  USA  2018    33.880045
6809  United States of America  USA  2019    33.873486
6810  United States of America  USA  2020    33.866926

In [29]:
# Filter out df to only include the years 1990 to 2020

df2 = df[(df['Year'] >= 1990) & (df['Year'] <= 2020)]
print(f"Length of file before filter {len(df)} and after {len(df2)}")

Length of file before filter 7309 and after 7199

In [75]:
# find all countries named by the United Nations and define the string to process

countries = """
Afghanistan	004	AFG
Åland Islands	248	ALA
Albania	008	ALB
Algeria	012	DZA
American Samoa	016	ASM
Andorra	020	AND
Angola	024	AGO
Anguilla	660	AIA
Antarctica	010	ATA
Antigua and Barbuda	028	ATG
Argentina	032	ARG
Armenia	051	ARM
Aruba	533	ABW
Australia	036	AUS
Austria	040	AUT
Azerbaijan	031	AZE
Bahamas	044	BHS
Bahrain	048	BHR
Bangladesh	050	BGD
Barbados	052	BRB
Belarus	112	BLR
Belgium	056	BEL
Belize	084	BLZ
Benin	204	BEN
Bermuda	060	BMU
Bhutan	064	BTN
Bolivia	068	BOL
Bonaire, Sint Eustatius and Saba	535	BES
Bosnia and Herzegovina	070	BIH
Botswana	072	BWA
Bouvet Island	074	BVT
Brazil	076	BRA
British Indian Ocean Territory	086	IOT
British Virgin Islands	092	VGB
Brunei Darussalam	096	BRN
Bulgaria	100	BGR
Burkina Faso	854	BFA
Burundi	108	BDI
Cabo Verde	132	CPV
Cambodia	116	KHM
Cameroon	120	CMR
Canada	124	CAN
Cayman Islands	136	CYM
Central African Rep.	140	CAF
Chad	148	TCD
Chile	152	CHL
China	156	CHN
China, Hong Kong Special Administrative Region	344	HKG
China, Macao Special Administrative Region	446	MAC
Christmas Island	162	CXR
Cocos (Keeling) Islands	166	CCK
Colombia	170	COL
Comoros	174	COM
Congo	178	COG
Cook Islands	184	COK
Costa Rica	188	CRI
Côte d'Ivoire	384	CIV
Croatia	191	HRV
Cuba	192	CUB
Curaçao	531	CUW
Cyprus	196	CYP
Czechia	203	CZE
North Korea	408	PRK
Dem. Rep. Congo	180	COD
Denmark	208	DNK
Djibouti	262	DJI
Dominica	212	DMA
Dominican Republic	214	DOM
Ecuador	218	ECU
Egypt	818	EGY
El Salvador	222	SLV
Equatorial Guinea	226	GNQ
Eritrea	232	ERI
Estonia	233	EST
Eswatini	748	SWZ
Ethiopia	231	ETH
Falkland Islands (Malvinas)	238	FLK
Faroe Islands	234	FRO
Fiji	242	FJI
Finland	246	FIN
France	250	FRA
French Guiana	254	GUF
French Polynesia	258	PYF
French Southern Territories	260	ATF
Gabon	266	GAB
Gambia	270	GMB
Georgia	268	GEO
Germany	276	DEU
Ghana	288	GHA
Gibraltar	292	GIB
Greece	300	GRC
Greenland	304	GRL
Grenada	308	GRD
Guadeloupe	312	GLP
Guam	316	GUM
Guatemala	320	GTM
Guernsey	831	GGY
Guinea	324	GIN
Guinea-Bissau	624	GNB
Guyana	328	GUY
Haiti	332	HTI
Heard Island and McDonald Islands	334	HMD
Holy See	336	VAT
Honduras	340	HND
Hungary	348	HUN
Iceland	352	ISL
India	356	IND
Indonesia	360	IDN
Iran	364	IRN
Iraq	368	IRQ
Ireland	372	IRL
Isle of Man	833	IMN
Israel	376	ISR
Italy	380	ITA
Jamaica	388	JAM
Japan	392	JPN
Jersey	832	JEY
Jordan	400	JOR
Kazakhstan	398	KAZ
Kenya	404	KEN
Kiribati	296	KIR
Kuwait	414	KWT
Kyrgyzstan	417	KGZ
Laos	418	LAO
Latvia	428	LVA
Lebanon	422	LBN
Lesotho	426	LSO
Liberia	430	LBR
Libya	434	LBY
Liechtenstein	438	LIE
Lithuania	440	LTU
Luxembourg	442	LUX
Madagascar	450	MDG
Malawi	454	MWI
Malaysia	458	MYS
Maldives	462	MDV
Mali	466	MLI
Malta	470	MLT
Marshall Islands	584	MHL
Martinique	474	MTQ
Mauritania	478	MRT
Mauritius	480	MUS
Mayotte	175	MYT
Mexico	484	MEX
Micronesia (Federated States of)	583	FSM
Monaco	492	MCO
Mongolia	496	MNG
Montenegro	499	MNE
Montserrat	500	MSR
Morocco	504	MAR
Mozambique	508	MOZ
Myanmar	104	MMR
Namibia	516	NAM
Nauru	520	NRU
Nepal	524	NPL
Netherlands	528	NLD
New Caledonia	540	NCL
New Zealand	554	NZL
Nicaragua	558	NIC
Niger	562	NER
Nigeria	566	NGA
Niue	570	NIU
Norfolk Island	574	NFK
North Macedonia	807	MKD
Northern Mariana Islands	580	MNP
Norway	578	NOR
Oman	512	OMN
Pakistan	586	PAK
Palau	585	PLW
Panama	591	PAN
Papua New Guinea	598	PNG
Paraguay	600	PRY
Peru	604	PER
Philippines	608	PHL
Pitcairn	612	PCN
Poland	616	POL
Portugal	620	PRT
Puerto Rico	630	PRI
Qatar	634	QAT
South Korea	410	KOR
Moldova	498	MDA
Réunion	638	REU
Romania	642	ROU
Russia	643	RUS
Rwanda	646	RWA
Saint Barthélemy	652	BLM
Saint Helena	654	SHN
Saint Kitts and Nevis	659	KNA
Saint Lucia	662	LCA
Saint Martin (French Part)	663	MAF
Saint Pierre and Miquelon	666	SPM
Saint Vincent and the Grenadines	670	VCT
Samoa	882	WSM
San Marino	674	SMR
Sao Tome and Principe	678	STP
Sark	680	
Saudi Arabia	682	SAU
Senegal	686	SEN
Serbia	688	SRB
Seychelles	690	SYC
Sierra Leone	694	SLE
Singapore	702	SGP
Sint Maarten (Dutch part)	534	SXM
Slovakia	703	SVK
Slovenia	705	SVN
Solomon Is.	090	SLB
Somalia	706	SOM
South Africa	710	ZAF
South Georgia and the South Sandwich Islands	239	SGS
S. Sudan	728	SSD
Spain	724	ESP
Sri Lanka	144	LKA
Palestine	275	PSE
Sudan	729	SDN
Suriname	740	SUR
Svalbard and Jan Mayen Islands	744	SJM
Sweden	752	SWE
Switzerland	756	CHE
Syria	760	SYR
Tajikistan	762	TJK
Taiwan\t158\tTWN
Thailand	764	THA
Timor-Leste\t626	TLS
Togo	768	TGO
Tokelau	772	TKL
Tonga	776	TON
Trinidad and Tobago	780	TTO
Tunisia	788	TUN
Turkey	792	TUR
Turkmenistan\t795	TKM
Turks and Caicos Islands	796	TCA
Tuvalu	798	TUV
Uganda	800	UGA
Ukraine	804	UKR
United Arab Emirates	784	ARE
United Kingdom	826	GBR
Tanzania	834	TZA
United States Minor Outlying Islands	581	UMI
United States of America	840	USA
United States Virgin Islands	850	VIR
Uruguay	858	URY
Uzbekistan	860	UZB
Vanuatu	548	VUT
Venezuela	862	VEN
Vietnam	704	VNM
Wallis and Futuna Islands	876	WLF
Western Sahara	732	ESH
Yemen	887	YEM
Zambia	894	ZMB
Zimbabwe
"""

In [77]:
# listing all countries and code so on
listCountriesAndMore = re.split('\t|\n', countries)
# filter for countries as they are every third element 
# starting from id=1
listCountries = listCountriesAndMore[1::3]
listCountries

['Afghanistan',
 'Åland Islands',
 'Albania',
 'Algeria',
 'American Samoa',
 'Andorra',
 'Angola',
 'Anguilla',
 'Antarctica',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Aruba',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Bolivia',
 'Bonaire, Sint Eustatius and Saba',
 'Bosnia and Herzegovina',
 'Botswana',
 'Bouvet Island',
 'Brazil',
 'British Indian Ocean Territory',
 'British Virgin Islands',
 'Brunei Darussalam',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cabo Verde',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cayman Islands',
 'Central African Rep.',
 'Chad',
 'Chile',
 'China',
 'China, Hong Kong Special Administrative Region',
 'China, Macao Special Administrative Region',
 'Christmas Island',
 'Cocos (Keeling) Islands',
 'Colombia',
 'Comoros',
 'Congo',
 'Cook Islands',
 'Costa Rica',
 "Côte d'Ivoire",
 'Croatia',
 'Cuba',
 'Curaçao',
 'Cyprus',
 'Czechia',
 'North Korea',
 'Dem. Rep. Congo',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Eswatini',
 'Ethiopia',
 'Falkland Islands (Malvinas)',
 'Faroe Islands',
 'Fiji',
 'Finland',
 'France',
 'French Guiana',
 'French Polynesia',
 'French Southern Territories',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Gibraltar',
 'Greece',
 'Greenland',
 'Grenada',
 'Guadeloupe',
 'Guam',
 'Guatemala',
 'Guernsey',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Heard Island and McDonald Islands',
 'Holy See',
 'Honduras',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Isle of Man',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jersey',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'Kuwait',
 'Kyrgyzstan',
 'Laos',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Marshall Islands',
 'Martinique',
 'Mauritania',
 'Mauritius',
 'Mayotte',
 'Mexico',
 'Micronesia (Federated States of)',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Montserrat',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nauru',
 'Nepal',
 'Netherlands',
 'New Caledonia',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'Niue',
 'Norfolk Island',
 'North Macedonia',
 'Northern Mariana Islands',
 'Norway',
 'Oman',
 'Pakistan',
 'Palau',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Pitcairn',
 'Poland',
 'Portugal',
 'Puerto Rico',
 'Qatar',
 'South Korea',
 'Moldova',
 'Réunion',
 'Romania',
 'Russia',
 'Rwanda',
 'Saint Barthélemy',
 'Saint Helena',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Martin (French Part)',
 'Saint Pierre and Miquelon',
 'Saint Vincent and the Grenadines',
 'Samoa',
 'San Marino',
 'Sao Tome and Principe',
 'Sark',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Singapore',
 'Sint Maarten (Dutch part)',
 'Slovakia',
 'Slovenia',
 'Solomon Is.',
 'Somalia',
 'South Africa',
 'South Georgia and the South Sandwich Islands',
 'S. Sudan',
 'Spain',
 'Sri Lanka',
 'Palestine',
 'Sudan',
 'Suriname',
 'Svalbard and Jan Mayen Islands',
 'Sweden',
 'Switzerland',
 'Syria',
 'Tajikistan',
 'Taiwan',
 'Thailand',
 'Timor-Leste',
 'Togo',
 'Tokelau',
 'Tonga',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Turks and Caicos Islands',
 'Tuvalu',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'Tanzania',
 'United States Minor Outlying Islands',
 'United States of America',
 'United States Virgin Islands',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Venezuela',
 'Vietnam',
 'Wallis and Futuna Islands',
 'Western Sahara',
 'Yemen',
 'Zambia',
 'Zimbabwe']

In [78]:
# filter df2 so only countries from listCountries are included

df_TrueCountries = df2[df2['Country'].isin(listCountries)]
print("Length with only UN territories:",df_TrueCountries.__len__())

Length with only UN territories: 6345

In [80]:
# save TrueCountries to csv

df_TrueCountries.to_csv('./data/percent-forest-cover_clean.csv', index=False)

In [79]:
df["Country"].unique().__len__() - df_TrueCountries["Country"].unique().__len__()

30